# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  Home

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'LocalDirectory'
    jdkFile: 'C:\Users\Thurobrand\agents\OpenJDK11U-jdk_x64_windows_hotspot_11.0.16.1_1.zip'
    jdkDestinationDirectory: 'C:\Users\Thurobrand\agents\java'
    cleanDestinationDirectory: true
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    workingDirectory: ''
    tasks: 'jar'
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'Resource Group Thurobrand'
    appType: 'functionApp'
    appName: 'ThurSpringFunc'
    package: '$(System.DefaultWorkingDirectory)/**/*.jar'
    deploymentMethod: 'auto'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 1.11
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
