# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  Home

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    workingDirectory: 'build\lib'
    tasks: 'build'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 1.11
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false